### ISSUE TITLE
Clarification on Execution Mode and Applicability of CCM_MADRL in Distributed Scenarios

### ISSUE THREAD

**Issue by Reeseee** [TesfayZ/CCM_MADRL_MEC#10]
Dear authors,  

First of all, I would like to express my appreciation for your excellent work on CCM_MADRL. The framework is well-designed, and its implementation is both insightful and innovative.  

I have a question regarding the execution mode of CCM_MADRL. While CCM_MADRL appears to share similarities with MADDPG, which employs a "centralized training and decentralized execution" paradigm, it seems that the critic in CCM_MADRL serves not only as a trainer but also as an action selector, aggregating all state and action information. Based on this, my understanding is that CCM_MADRL operates as a "centralized training and centralized execution" model. Is this interpretation correct?  

Furthermore, I am interested in applying CCM_MADRL to a network with multiple servers and enabling distributed execution. However, if my understanding above is correct, it seems that CCM_MADRL's design might fundamentally prevent such an adaptation. Could you please share your thoughts or suggestions on this matter? Any insights or guidance would be greatly appreciated.  

Thank you in advance for your time and for your remarkable contribution to this area of research!  

Best regards,  
Reese

**Comment by TesfayZ** [comment]
Hi, thank you for the appreciation and interest vin our work.

Yes the our work has similarly with MADDPG but the critic in our work is
called a master agent and is used for both training (giving feedback to
actors) and selecting combinatorial action. This is not centralized
training and centralized execution. Is is centralized training but the
execution is distributed in the devices and the server. The client agents
run in the clients. And the master agent runs in the server.

To apply it to multiple servers, you need to redesign a new algorithm. Our
work is designed for a single server and multiple users. The extension to
multiple servers is mentioned ad future work.

**Comment by TesfayZ** [comment]
1. The constraint for the combinatorial action selection is not only K. It
is also the storage contraintbof the server.  It continuous selecting until
either of the contraints are met. See the code, the algorithm, and the
description of the paper.

2. The client agents can make independent decision if Xc is less than 0.5.
Otherwise, they delegate the master agent to make decision on their task.
So, it is hybrid execution. Read the paper in detail. You misnderstand like
the master participates always. But not. If all clients have Xc of less
than 0.5 the master doesn't participate.
